In [1]:
import numpy as np

# create a rank 1 array //// 1D array

In [2]:
a=np.array([0,1,2])

In [3]:
a

array([0, 1, 2])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
#this will print the dimension of the array
print(a.shape)

(3,)


In [6]:
print(a[0])
print(a[1])
print(a[2])

0
1
2


In [7]:
# change an element of the array
a[0]=5

In [8]:
a

array([5, 1, 2])

# 2D array

In [9]:
b=np.array([[1,2,3],[4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [12]:
b[0,0],b[0,1],b[0,2],b[1,0],b[1,1],b[1,2]

(1, 2, 3, 4, 5, 6)

In [13]:
print(b[0,0],b[0,1],b[0,2],b[1,0],b[1,1],b[1,2])
print(b[0,0],b[0,1],b[0,2])

1 2 3 4 5 6
1 2 3


# Creating numpy array

In [14]:
# create a n*n array of all zeros
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
# Create a 2*2,3*3 array of all ones
a=np.ones((2,2))
print(a)
b=np.ones((4,4))
b


[[1. 1.]
 [1. 1.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# Create a 3*3, 2*2 constant array
a=np.full((3,3),7)
print(a)
a=np.full((2,2),7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[7 7]
 [7 7]]


In [18]:
# Create a 3*3 array filled with random values
d=np.random.random((3,3))
print(d)

[[0.04931191 0.82348503 0.32125855]
 [0.1402778  0.48431887 0.40139905]
 [0.57954204 0.3234866  0.7835519 ]]


In [19]:
# create a 3 3 identity mtrix
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# Convert list to array
l=[1,2,3,4,5]
a=np.array(l)
print(a)

f = np.array([1,2,3,4,5])
print(f)

[1 2 3 4 5]
[1 2 3 4 5]


In [21]:
# arange() will create arrays with regular increment values
a=np.arange(20)
a
#print(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
# array with mixing of tuple and list

a=np.array([[0,1,2.0],[0,0,0],[1+1j,3,2]])
a

array([[0.+0.j, 1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j, 2.+0.j]])

In [23]:
# create an array of range with float data type
a=np.arange(1,8,dtype=np.float)
print(a)

a=np.arange(8,dtype=np.int)
print(a)


[1. 2. 3. 4. 5. 6. 7.]
[0 1 2 3 4 5 6 7]


C:\Users\WIN\AppData\Local\Temp/ipykernel_11192/1086428437.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.arange(1,8,dtype=np.float)
C:\Users\WIN\AppData\Local\Temp/ipykernel_11192/1086428437.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1

# linspace() will create arrays with a specified number of items which are spaced equally between the specified beginning and ending values

In [24]:
a=np.linspace(2.,4.,5)
a

array([2. , 2.5, 3. , 3.5, 4. ])

# indices() create a set of arrays stacked as a one higher dimensional array , one per dimension with each reporesnting variation in that variation

In [25]:
a=np.indices((2,2))
print(a)
a=np.indices((3,3))
print(a)
a=np.indices((4,4))
print(a)

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]


# Data types
An array is a collection of items of the same data type and NumPy supports and provides 
built-in functions to construct arrays with optional arguments to explicitly specify 
required datatypes

In [30]:
x=np.array([0,1])
y=np.array([2.0,3.0])
print(x.dtype)
print(y.dtype)

int32
float64


In [34]:
# Force a particular data type
x=np.array([5,6],dtype=np.int64)
print(x.dtype)

int64


# Array Indexing
Standard Python x[obj] syntax can be 
used to index NumPy array, where x is the array and obj is the selection.
There are three kinds of indexing available:
•	 Field access
•	 Basic slicing
•	 Advanced indexing

# Field Access
If the ndarray object is a structured array, the fields of the array can be accessed by 
indexing the array with strings, dictionary like. Indexing x[‘field-name’] returns a new 
view to the array, which is of the same shape as x, except when the field is a subarray, but 
of data type x.dtype[‘field-name’] and contains only the part of the data in the specified 
field

In [36]:
x=np.zeros((3,3),dtype=[('a',np.int32),('b',np.float64,(3,3))])
print(x)

[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]


In [39]:
print("x['a'].shape:",x['a'].shape)
print("x['a'].dtype:",x['a'].dtype)
print("x['b'].shape:",x['b'].shape)
print("x['b'].shape:",x['b'].dtype)

x['a'].shape: (3, 3)
x['a'].dtype: int32
x['b'].shape: (3, 3, 3, 3)
x['b'].shape: float64


# Basic Slicing
NumPy arrays can be sliced, similar to lists. You must specify a slice for each dimension of 
the array as the arrays may be multidimensional.
The basic slice syntax is i: j: k, where i is the starting index, j is the stopping index, 
and k is the step and k is not equal to 0. 

In [42]:
x=np.array([5,6,7,8,9])
x[1:7]


array([6, 7, 8, 9])

In [45]:
x[1:7:2]
x[1:7:3]

array([6, 9])

In [49]:
print(x[2:])
x[:2]

[7 8 9]


array([5, 6])

In [54]:
x[-2:5:1]

array([8, 9])

In [53]:
x[-1:1:-1]

array([9, 8, 7])

In [65]:
y=np.array([[[1],[2],[3]],[[4],[5],[6]]])
y


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [66]:
y[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
print("Shape of y:",y.shape)

Shape of y: (2, 3, 1)


In [59]:
y=np.array([[[1,1],[2,1],[3,1]],[[4,2],[5,2],[6,2]]])
y

array([[[1, 1],
        [2, 1],
        [3, 1]],

       [[4, 2],
        [5, 2],
        [6, 2]]])

In [60]:
print("Shape of y:",y.shape)

Shape of y: (2, 3, 2)


In [61]:
y[1:3]

array([[[4, 2],
        [5, 2],
        [6, 2]]])

In [62]:
y[1][0]

array([4, 2])

In [63]:
x[...,0]

array(5)

In [64]:
y[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

# Create a 2D array with shape 3,4 

In [67]:
a=np.array([[5,6,7,8],[1,2,3,4],[9,10,11,12]])
a

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [68]:
print(a[0][0],a[1][0],a[2][0])

5 1 9


In [71]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2)

b=a[:2,1:3]
b


array([[6, 7],
       [2, 3]])

In [72]:
b.shape

(2, 2)

In [ ]:
#A slice of an array is a view into the same data, so modifying itwill modify the original array

In [74]:
print(a[0][1])
b[0,0]=77
a

77


array([[ 5, 77,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

# Middle row Column array
 
 can be accessed in two ways. 1) Slices along with integer 
indexing will result in an arry of lower rank. 2) Using only slices will 
result in same rank array

In [77]:
row1=a[1,:]
print(row1)
print(row1.shape)

[1 2 3 4]
(4,)


In [78]:
row2=a[1:2]
print(row2)
print(row2.shape)

[[1 2 3 4]]
(1, 4)


In [79]:
row1=a[:,1]
print(row1)
print(row1.shape)

[77  2 10]
(3,)


In [80]:
row2=a[:,1:2]
print(row2)
print(row2.shape)

[[77]
 [ 2]
 [10]]
(3, 1)


# Advanced Indexing
Integer array indexing: Integer array indexing allows you to construct random arrays and 
other arrays.

In [85]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [86]:
print(a[0,1],[0,1])

2 [0, 1]


In [87]:
print(a[0,1],a[0,1])

2 2


In [99]:
print(np.array([a[0,0],a[1,1]]))
print(np.array([a[0,0],[1,1]]))
print([a[0,0],a[1,1]])
print(a[0,0],a[1,1])
print(a[[0,0],[1,1]])

[1 4]
[1 list([1, 1])]
[1, 4]
1 4
[2 2]


C:\Users\WIN\AppData\Local\Temp/ipykernel_11192/3442593253.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array([a[0,0],[1,1]]))


# Boolean Array indexing

In [107]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,2],[3,4],[5,6]])

print(b>5)

[[False False]
 [False False]
 [False  True]]


In [109]:
print(a>2)


[[False False]
 [ True  True]
 [ True  True]]


In [108]:
print(b>5)

[[False False]
 [False False]
 [False  True]]


In [102]:
print(a[a>2])

[3 4 5 6]


# Array Math

In [110]:
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8],[9,10],[11,12]])

In [111]:
x+y

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [112]:
print(np.add(x,y))

[[ 8 10]
 [12 14]
 [16 18]]


In [113]:
x-y

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [114]:
np.subtract(x,y)

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [115]:
x*y

array([[ 7, 16],
       [27, 40],
       [55, 72]])

In [116]:
np.multiply(y,x)

array([[ 7, 16],
       [27, 40],
       [55, 72]])

In [117]:
x/y

array([[0.14285714, 0.25      ],
       [0.33333333, 0.4       ],
       [0.45454545, 0.5       ]])

In [118]:
np.divide(x,y)

array([[0.14285714, 0.25      ],
       [0.33333333, 0.4       ],
       [0.45454545, 0.5       ]])

In [120]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [122]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
a=np.array([9,10])
b=np.array([11,12])

# Inner products of vectors

In [123]:
a.dot(b)

219

In [124]:
np.dot(a,b)

219

In [125]:
a

array([ 9, 10])

In [126]:
b

array([11, 12])

# Matrix/vector product

In [127]:
x.dot(a)

array([29, 67])

In [128]:
np.dot(x,a)

array([29, 67])

# Matrix/Matrix product

In [129]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [130]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

# Sum function

In [131]:
x=np.array([[1,2],[3,4]])

In [132]:
# Compute sum of all elements
print(np.sum(x))


10


In [133]:
# Compute sum of each column
print(np.sum(x, axis=0))


[4 6]


In [134]:
# Compute sum of each row
print(np.sum(x, axis=1))

[3 7]


# Transpose Function

In [135]:
x=np.array([[1,2],[3,4]])

In [136]:
x.T

array([[1, 3],
       [2, 4]])

In [137]:
np.transpose(x)

array([[1, 3],
       [2, 4]])

In [138]:
c=np.array([1,2,3,4])

In [139]:
c.T

array([1, 2, 3, 4])

# Broadcasting
Broadcasting enables arithmetic operations to be performed between different shaped 
arrays

In [150]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# create a vector
v=np.array([1,0,1])
# create an empty matrix with the same shape as a
b=np.empty_like(a)
c=np.empty_like(a)

In [151]:
a[0,:] # means row extract

array([1, 2, 3])

In [152]:
a[:,0] # column extract

array([1, 4, 7])

In [153]:
a[0 :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
#Nowq, adding the vector v to each row of the natrix a with an explicit loop
for i in range(3):
    b[i,:]=a[i,:]+v
b

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [156]:
#Nowq, adding the vector v to each column of the natrix a with an explicit loop
for i in range(3):
    c[:,i]=a[:,i]+v
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 8,  9, 10]])

# Broadcasting for large matrix

In [157]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
# stack 3 copies of v on top of each other

vv=np.tile(v,(3,1))
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [160]:
b=a+vv
b

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [161]:
#broadcasting using numpy
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
v

array([1, 0, 1])

In [164]:
d=np.empty_like(a)
d

array([[1936482592, 1701978223, 1852994932],
       [ 170812517,  540680311, 1634890337],
       [1768710009,  539780459, 1885431923]])

In [165]:
d=a+v
d

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

# Application of Broadcasting

In [166]:
# compute outer products of vector
# v has shape 3
v=np.array([1,2,3])
# w has shape 2
w=np.array([4,5])
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w


In [167]:
v=np.reshape(v,(3,1))

In [168]:
v

array([[1],
       [2],
       [3]])

In [169]:
v*w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

# Add a vector to each row of a matrix

In [171]:
x=np.array([[1,2,3],[4,5,6]])

In [173]:
v=np.reshape(v,(1,3))

In [174]:
x+v

array([[2, 4, 6],
       [5, 7, 9]])

# Add a vector to each column of a matrix

In [175]:
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column
x

array([[1, 2, 3],
       [4, 5, 6]])

In [181]:
e=(x.T+w)

In [182]:
e.T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [184]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output
w=np.reshape(w,(2,1))
w

array([[4],
       [5]])

In [185]:
x+w

array([[ 5,  6,  7],
       [ 9, 10, 11]])

# Multiply a matrix by constant

In [186]:
x*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])